### ISSUE TITLE
配置appId和appkey不方便

### ISSUE THREAD

**Issue by 1512751361** [Aicxz/react-native-xiaomi-push#1]
![MHC4L9 %MB9`1_9JE9$BT6U](https://user-images.githubusercontent.com/24776858/57191417-f7199e80-6f57-11e9-86f6-74b5a0282359.png)
这个appId和appkey在插件写死了？可以修改成可配置的插件么？

**Comment by Aicxz** [comment]
已修复，请更新到v1.1.0版本，参考README.md进行配置
